version: '3.6'

services:
   kafka:
     image: spotify/kafka
     container_name: pptk_kafka
     ports:
         - 2181:2181
         - 9092:9092
     environment:
         ADVERTISED_PORT: 9092
         ADVERTISED_HOST: ${DOCKER_HOST_IP}  # For accessing kafka queue from localhost
     restart: always
     deploy:
        replicas: 1
        restart_policy:
           condition: any
           delay: 5s
           max_attempts: 3
           window: 30s
        resources:
           limits:
             cpus: '0.1'
             memory: 50M
           reservations:
             cpus: '0.01'
             memory: 10M

   front:
     build:
        context: ./front
     image: front:0.0.1
     container_name: pptk_front
     restart: always
     deploy:
        replicas: 3
        restart_policy:
           condition: any
           delay: 5s
           max_attempts: 3
           window: 30s
        resources:
           limits:
             cpus: '0.1'
             memory: 50M
           reservations:
             cpus: '0.01'
             memory: 10M
     healthcheck:
        test: ["CMD", "curl", "-f", "http://front:8000"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s
     ports:
       - "80:8000"

   verifier:
     build:
        context: ./verifier
     image: verifier:0.0.1
     container_name: pptk_verifier
     deploy:
        replicas: 3
        restart_policy:
           condition: any
           delay: 5s
           max_attempts: 3
           window: 30s
        resources:
           limits:
             cpus: '0.1'
             memory: 50M
           reservations:
             cpus: '0.01'
             memory: 10M
     healthcheck:
        test: ["CMD", "curl", "-f", "http://verifier:8000/api/v1/verify?image=https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s
     restart: always

   slides:
     build:
        context: ./slides
     image: slides:0.0.1
     container_name: pptk_slides
     deploy:
        replicas: 3
        restart_policy:
           condition: any
           delay: 5s
           max_attempts: 3
           window: 30s
        resources:
           limits:
             cpus: '0.1'
             memory: 50M
           reservations:
             cpus: '0.01'
             memory: 10M
     healthcheck:
        test: ["CMD", "curl", "-f", "http://slides:8000/api/v1/slides/random/3"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s
     restart: always

   admin:
      build:
         context: ./admin
      image: admin:0.0.1
      container_name: pptk_admin
      environment:
         - BASIC_AUTH_USERNAME=${ADMIN_USERNAME}
         - BASIC_AUTH_PASSWORD=${ADMIN_PASSWORD}
      deploy:
         replicas: 3
         restart_policy:
            condition: any
            delay: 5s
            max_attempts: 3
            window: 30s
         resources:
            limits:
              cpus: '0.1'
              memory: 50M
            reservations:
              cpus: '0.01'
              memory: 10M
      healthcheck:
         test: ["CMD", "curl", "-f", "http://${ADMIN_USERNAME}:${ADMIN_PASSWORD}@admin:8000"]
         interval: 1m30s
         timeout: 10s
         retries: 3
         start_period: 40s
      restart: always
      ports:
       - "8080:8000"

   spider:
     build:
        context: ./spider
     image: spider:0.0.1
     container_name: pptk_spider
     deploy:
        replicas: 3
        restart_policy:
           condition: any
           delay: 5s
           max_attempts: 3
           window: 30s
        resources:
           limits:
             cpus: '0.1'
             memory: 50M
           reservations:
             cpus: '0.01'
             memory: 10M
     restart: always
